{% set version = "0.2.2.post3" %}

package:
  name: pysvg-py3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pysvg-py3/pysvg-py3-{{ version }}.tar.gz
  sha256:  a1183aa5d89871298c11f25d28640edc3798b6ed1e2b2a95c30d35985d6431d0

build:
  number: 3
  skip: true  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pysvg.core
    - pysvg.shape
    - pysvg.builders

about:
  home: https://github.com/alorence/pysvg-py3
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: "Python 3 portage of pysvg"

extra:
  recipe-maintainers:
    - zachcp
